name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
          openai_light_model: gpt-4o
          openai_heavy_model: o3
          language: ja-JP
          review: |
            日本語を使用してください。
            以下に記載した観点からレビューを行ってください。
            ただし、改善点がなければ回答は不要です。
            クエリやgormが利用されている場合、以下2つの観点から改善提案してください。
            - クエリそのもののパフォーマンス改善
            - 検索対象テーブルにインデックスを追加すべきカラムがあるか
            その他ファイル対して、以下の観点でレビューしてください。
            - 命名は分かりやすく実態を表しているか
            - typo
            - 可読性
            - セキュリティ上の脆弱性がないか
            - トランザクションの貼り方が適切か
            - nilチェックが適切にされているか
            - 理解しにくい、または実装と命名が乖離している箇所があるか
            - 冗長なコードがないか
            - メソッド名・関数名だけで実装が理解しにくい場合、分かりやすい日本語でコメントされているか
            - ネストが深い（3以上）条件文などがないか
          summarize: |
            最終的な回答を `markdown` フォーマットで以下の内容で書いてください:
            - 高レベルの要約（特定のファイルではなく、全体的な変更点についてのコメント日本語200文字以内)
            - ファイルとその要約のtableを書くこと
            - 同じような変更点のあるファイルをスペースを節約するために、同じような変更を持つファイルを1つの行にまとめてよい
            この要約は、GitHub の PullRequest にコメントとして追加されるので、追加コメントは避けること
          summarize_release_notes: |
            この PullRequest のために `markdown` フォーマットで簡潔なリリースノートを作成すること。
            コードの目的とユーザーストーリーに焦点を当てること。
            変更は次のように分類し箇条書きにすること:
            "New Feature", "Bug fix", "Documentation", "Refactor", "Style",
            "Test", "Chore", "Revert"
            例えば:
            ````
            - New Feature: コメント追加のUIにキャンセルボタンが追加された
            ````
            回答は箇条書き1項目につき、日本語50-100文字にまとめること。
            この回答はリリースノートでそのまま使用されます。
            リリースノートの下に、この PullRequest の変更点についての短いお祝いのポエムを追加してください。
            このポエムを引用（ `>` ）として追加してください。ポエムには絵文字を使用できる
